source :gemcutter

gem 'rails',                '2.3.5'
gem 'mongo_mapper',         '0.7.6'
gem 'RubyInline'
gem 'image_science'
gem 'magic'
gem 'carrierwave',          '0.4.4'
gem 'bson_ext',             '1.0.0'
gem 'devise'
gem 'will_paginate'
gem 'haml'
gem 'mongomapper_ext'
gem 'scopify'
gem 'fleakr'
gem 'navvy'
gem 'postmark-rails'
gem 'bundler'
gem 'mongrel'
gem 'matsimitsu-risosu-san'
gem 'i18n'
gem 'tzinfo'
group :test do
  gem 'rspec-rails', '1.3.2'
  gem 'faker'
  gem 'steak'
  gem 'capybara'
  gem 'machinist_mongo', '1.1.0'
end