# config/database.yml

development:
  adapter: mongodb
  database: mysnaplog_development
  host: localhost

test:
  adapter: mongodb
  database: mysnaplog_test
  host: localhost

production:
  adapter: mongodb
  database: mysnaplog_production
  host: localhost